apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
  labels:
    app: movies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: movie-app
        imagePullPolicy: Always
        image: mullet999/movie_app
        ports:
        - containerPort: 3000
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: movie-app
spec:
  selector:
    app: movies
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
